config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/download/:type', to: 'home#download_forecast', as: :download,
    type: /csv|json/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'open_weather_api'

class HomeController < ApplicationController
  def index
    @forecast = OpenWeatherApi.get_daily_forecast
  end

  def download_forecast
    type = params[:type]
    send_data OpenWeatherApi.get_file(type),
      filename: "forecast.#{type}",
      type: define_content_type(type)
  end

  private

  def define_content_type(type)
    case type
      when 'json'
        'application/json'
      when 'csv'
        'text/csv'
      else
        'text/plain'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_forecast.html.erb
<% @forecast.each do |value| %>
  <p>
    City: <%= value[:city] %></br>
    From: <%= value[:timeFrom].sub(/T/, ' ') %></br>
    To: <%= value[:timeTo].sub(/T/, ' ') %></br>
    Temperature: <%= value[:temperature] %></br>
    Pressure: <%= value[:pressure] %></br>
    Humidity: <%= value[:humidity] %></br>
    Wind <%= value[:windDirection] %> <%= value[:windSpeed] %></br>
  </p>
<% end %>

app/views/home/index.html.erb
<%= link_to 'Download CSV', download_url('csv'), method: :post %>
<%= link_to 'Download JSON', download_url('json'), method: :post %>
</br>
<%= render 'forecast' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>